/** @type {Object<string, string>} */
export const errorSynonyms = {
  'Not Found': 'request/not-found',
  'Bad Request': 'request/malformed',
  Unauthorized: 'auth/unauthorized',
  'Payment Required': 'payment/required',
  Forbidden: 'auth/forbidden',
  'Method Not Allowed': 'request/method-not-allowed',
  'Not Acceptable': 'request/not-acceptable',
  'Request Timeout': 'request/timeout',
  Conflict: 'request/conflict',
  Gone: 'data/not-found',
  'Length Required': 'request/length-required',
  'Precondition Failed': 'request/precondition-failed',
  'Payload Too Large': 'request/too-large',
  'URI Too Long': 'request/uri-too-long',
  'Unsupported Media Type': 'request/unsupported-media-type',
  'Range Not Satisfiable': 'request/range-not-satisfiable',
  'Expectation Failed': 'request/expectation-failed',
  'I\'m a teapot': 'me/teapot',
  'Unprocessable Entity': 'request/unprocessable-entity',
  Locked: 'data/locked',
  'Failed Dependency': 'request/failed-dependency',
  'Unordered Collection': 'data/unordered',
  'Upgrade Required': 'request/update-required',
  'Precondition Required': 'request/precondition-required',
  'Too Many Requests': 'request/rate-limit',
  'Request Header Fields Too Large': 'request/header-fields-too-large',
  'Unavailable For Legal Reasons': 'request/unavailable-legal',
  'Internal Server Error': 'server/internal-server-error',
  'Not Implemented': 'server/not-implemented',
  'Bad Gateway': 'gateway/invalid',
  'Service Unavailable': 'server/unavailable',
  'Gateway Timeout': 'gateway/timeout',
  'Insufficient Storage': 'storage/insufficient'
};
